name: Proposal
description: Create a new Idea Proposal
title: "[Proposal]: "
labels: [Proposal, Pending]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What's your idea about?
      description: What idea are you interested on working on and leading?
      placeholder: Lay your ideas out!
    validations:
      required: true
      