name: Proposal
description: Create a new project proposal
title: "[Project Name]"
labels: [Proposal, Pending]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a project idea!\nPlease put a temporary name for your idea in the title line above that reflects the scope of the project. We'll use this name to reference your idea when voting!
  - type: input
    id: name
    attributes:
      label: What is your full name?
      description: We need to know who to bring up during the interest meeting!
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: What is your Knights email?
      description: If we need to communicate with you prior to the meeting, we will send you an email.
    validations:
      required: true
  - type: dropdown
    id: present
    attributes:
      label: Are you interested in presenting your idea at the interest meeting?
      description: This doesn't have to be final.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: Write down your proposal idea here!
    id: proposal
    validations:
      required: true
